let menuItemsData = [
  {
    id: "minuman1",
    kategori: "minuman",
    img: "/minuman/AFFOGATO.JPG",
    name: "Affogato",
    price: 12500,
  },
  {
    id: "minuman2",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-CAFE-LATTE.JPG",
    name: "Hot Iced Cafe Late",
    price: 12500,
  },
  {
    id: "minuman3",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-CAPPUCINO.JPG",
    name: "Hot Iced Cappucino",
    price: 12500,
  },
  {
    id: "minuman4",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-CHOCOLATE.JPG",
    name: "Hot Iced Chocolate",
    price: 12500,
  },
  {
    id: "minuman5",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-COFFEE-BOMBON.JPG",
    name: "Hot Iced Coffe Bombon",
    price: 12500,
  },
  {
    id: "minuman6",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-KOPI-SUSU-ANDALAN.JPG",
    name: "Hot Iced Kopi Susu Andalan",
    price: 12500,
  },
  {
    id: "minuman7",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-KOPI-SUSU-CANTI-MANIS.JPG",
    name: "Hot Iced Kopi Susu Canti Manis",
    price: 12500,
  },
  {
    id: "minuman8",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-KOPI-SUSU-PATTABA.JPG",
    name: "Hot Iced Kopi Susu Pattaba",
    price: 12500,
  },
  {
    id: "minuman9",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-KOPI-SUSU-WARKOP.JPG",
    name: "Hot Iced Kopi Susu Warkop",
    price: 12500,
  },
  {
    id: "minuman10",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-KOPI-VANILLA.JPG",
    name: "Hot Iced Kopi Vanilla",
    price: 12500,
  },
  {
    id: "minuman11",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-LEMON-TEA.JPG",
    name: "Hot Iced Lemon Tea",
    price: 12500,
  },
  {
    id: "minuman12",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-LYCHEE-TEA.JPG",
    name: "Hot Iced Lychee Tea",
    price: 12500,
  },
  {
    id: "minuman13",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-MATCHA-LATTE.JPG",
    name: "Hot Iced Matcha Latte",
    price: 12500,
  },
  {
    id: "minuman14",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-RED-VELVET-LATTE.JPG",
    name: "Hot Iced Red Velvet Latte",
    price: 12500,
  },
  {
    id: "minuman15",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-SUSU-SEGAR.JPG",
    name: "Hot Iced Susu Segar",
    price: 12500,
  },
  {
    id: "minuman16",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-TARO-LATTE.JPG",
    name: "Hot Iced Taro Latte",
    price: 12500,
  },
  {
    id: "minuman17",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-TEA.JPG",
    name: "Hot Iced Tea",
    price: 12500,
  },
  {
    id: "minuman18",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-THAI-TEA.JPG",
    name: "Hot Iced Thai Tea",
    price: 12500,
  },
  {
    id: "minuman19",
    kategori: "minuman",
    img: "/minuman/HOT-ICED-VANILLA-LATTE.JPG",
    name: "Hot Iced Vanilla ",
    price: 12500,
  },
  {
    id: "minuman20",
    kategori: "minuman",
    img: "/minuman/ICED-SUSU-BLUEBERRY.JPG",
    name: "Iced Susu Blueberry",
    price: 12500,
  },
  {
    id: "minuman21",
    kategori: "minuman",
    img: "/minuman/ICED-SUSU-STRAWBERRY.JPG",
    name: "Iced Susu Strawberry",
    price: 12500,
  },
  {
    id: "minuman21",
    kategori: "minuman",
    img: "/minuman/VIETNAM-DRIP.JPG",
    name: "Vietnam Drip",
    price: 12500,
  },
  {
    id: "makanan1",
    kategori: "makanan",
    img: "/makanan/BALADO-FRENCH-FRIES.jpg",
    name: "Balado French Fries",
    price: 12500,
  },
  {
    id: "makanan2",
    kategori: "makanan",
    img: "/makanan/CARAMEL-POPCORN.jpg",
    name: "Caramel Popcorn",
    price: 12500,
  },
  {
    id: "makanan3",
    kategori: "makanan",
    img: "/makanan/CHICKEN-WING.jpg",
    name: "Chicken Wing",
    price: 12500,
  },
];